Feature:issue7:web_socket
TrSaka/asset-tracker pull request #8
Opened 2024-12-29 02:39 UTC by TrSaka

2025-01-01 02:39 UTC, TrSaka commented on lib/core/config/theme/extension/currency_widget_title_extension.dart
> +extension GetCurrencyTitle on String {
burası string classtan alınabilir

2025-01-01 02:47 UTC, TrSaka commented on lib/data/repository/web/web_socket_repository.dart
> +          if (index == -1) {
-1 enumlaştırılabilir

2025-01-01 02:48 UTC, TrSaka commented on lib/data/service/remote/web/web_socket_service.dart
> +            socket!.add('40');
'40' , '0' , len-1 ifadeleri statik olarak başka bir yere atanabilir

2025-01-02 09:33 UTC, ErenBal1 requested changes

2025-01-02 09:33 UTC, ErenBal1 commented on lib/presentation/view/widgets/currency_card_widget.dart
> +              "\t${currency.name}",
Buradaki 3 adet text widget tek bir yerde modellenebilir hepsi aynı parametreleri alıyor overflow ise nullable olabilir şeklinde alınabilir.

2025-01-02 14:00 UTC, TrSaka commented on lib/presentation/view/widgets/currency_card_widget.dart
> +              "\t${currency.name}",
Overflow durumunu Elipsis ile kontrole diyorum, textlerin styleları farklı olduğu için enum veya farklı bir tip ile style seçimi yapmam gerek widget içinde. Tespitin için teşekkürler.

2025-01-03 13:33 UTC, E-MRE approved these changes
Eline sağlık, kanala bir video gelirse müthiş olur

2025-01-03 18:04 UTC, merged